### ISSUE TITLE
Is there Bug in Preprocess.py?

### ISSUE THREAD

**Issue by Zhengyan-Sheng** [ms-dot-k/Visual-Context-Attentional-GAN#1]
After run the preprocess.py, i got the video the the top left part of the video rather than the lip centered. Is there bug in preprocess.py?

**Comment by ms-dot-k** [comment]
I have checked the preprocess.py but I can run it without problems.

Did you meet any error messages when you run the code? and what are your python version and OS system?

**Comment by Zhengyan-Sheng** [comment]
Thank for your reply! No error messages i meet when run the code.&nbsp;
I wander what the code in&nbsp;Preprocess.py in line 104 :&nbsp;aligned_video += [aligned_im[:256, :256, :]] for?&nbsp; aligned_im[:256, :256, :] that crop the left and top image?Do you want to reshape the image to [256,256] or for what? Thank you!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ms-dot-k/Visual-Context-Attentional-GAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月29日(星期天) 下午3:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ms-dot-k/Visual-Context-Attentional-GAN] Is there Bug in Preprocess.py? (Issue #1)





 
I have checked the preprocess.py but I can run it without problems.
 
Did you meet any error messages when you run the code? and what are your python version and OS system?

**Comment by ms-dot-k** [comment]
The preprocessing includes facial alignment.
Therefore, firstly the input faces are aligned to the reference face (based on the landmark in Ref_face.txt) through SimilarityTransform() and cv2.warpAffine().
After alignment, the faces are located in a size of 256x256 (since the reference face is originally 256x256 size).
Thus, we can crop the aligned face by taking only the top left 256x256 part.

I think your problem might be in the face alignment step.

**Comment by Zhengyan-Sheng** [comment]
I don't change any code in preprocess.py and the output video see annex(bbaf5a.mp4).&nbsp;


After i change the code
"aligned_video += [aligned_im[:256, :256, :]]&nbsp; " to "aligned_video += [aligned_im[:, :, :]]"&nbsp;
the output video see annex (bbaf5a_change.mp4).&nbsp;
You say "After alignment, the faces are located in a size of 256x256 (since the reference face is originally 256x256 size)." But from the output we see the faces are not located in a size of 256x256... And don't change anything in the code or Ref_face.txt or landmark.
So i thank if my original grid video dataset is different from yours? My original grid video see annex (ori_bbaf5a.mp4)?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ms-dot-k/Visual-Context-Attentional-GAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月29日(星期天) 下午3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ms-dot-k/Visual-Context-Attentional-GAN] Is there Bug in Preprocess.py? (Issue #1)





 
The preprocessing includes facial alignment.
 Therefore, firstly the input faces are aligned to the reference face (based on the landmark in Ref_face.txt) through SimilarityTransform() and cv2.warpAffine().
 After alignment, the faces are located in a size of 256x256 (since the reference face is originally 256x256 size).
 Thus, we can crop the aligned face by taking only the top left 256x256 part.
 
I think your problem might be in the face alignment step.

**Comment by ms-dot-k** [comment]
Can you email the files to ms.k@kaist.ac.kr?
I cannot find the annex. Thank you.

**Comment by ms-dot-k** [comment]
I have checked the files you sent.
The problem might be the landmark files are based on "basic GRID video (360x288)" but your GRID data is "High-resolution GRID video (720x576)". 

Can you try to change the preprocess.py as follows?
in line #100 
'source_lm = temp_lm'
to
'source_lm = temp_lm * 2'.

**Comment by Zhengyan-Sheng** [comment]
Thank you ! The bug is solved! Thank you !
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ms-dot-k/Visual-Context-Attentional-GAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月29日(星期天) 下午4:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ms-dot-k/Visual-Context-Attentional-GAN] Is there Bug in Preprocess.py? (Issue #1)





 
I have checked the files you sent.
 The problem might be the landmark files are based on "basic GRID video (360x288)" but your GRID data is "High-resolution GRID video (720x576)".
 
Can you try to change the preprocess.py as follows?
 in line #100
 'source_lm = temp_lm'
 to
 'source_lm = temp_lm * 2'.
