### ISSUE TITLE
STOI score

### ISSUE THREAD

**Issue by Yifan-Liang** [ms-dot-k/Visual-Context-Attentional-GAN#5]
Hello, i have downloaded your Pre-trained model checkpoints and then run the test_LRS.py. However, the stoi score we tested is 0.208, which is different from the provided score.

**Comment by ms-dot-k** [comment]
How did you extract the waveform from the original video? Maybe, the different waveform extraction cause the issue.

**Comment by ms-dot-k** [comment]
I have checked and I can get the same results. (using torch version 1.8).
Also, I extracted the audio from video by using the following command using ffmpeg.
```
ffmpeg -loglevel panic -nostdin -y -i {vid_name} -acodec pcm_s16le -ar 16000 -ac 1 {aud_name}'
```

**Comment by Yifan-Liang** [comment]
Thanks for your reply. My waveform extraction code is followed:
```
files = glob.glob(os.path.join(dir_name,'*','*','*.mp4'), recursive=True)
for k, v in enumerate(files):
    file_split = v.split(os.sep)
    file_split[7] = 'LRS2-BBC_audio'
    audio = '/'+os.path.join(*file_split)
    if not os.path.exists(os.path.split(audio)[0]):
        os.makedirs(os.path.split(audio)[0])
    subprocess.call(f'ffmpeg -y -i {v} -ac 1 -acodec pcm_s16le -ar 16000 { audio[:-4] + ".wav"}',
                    shell=True)
   print(f'{k}/{len(files)}')
```
It seems like same with the code you have provided. And I have aslo tried to downgrade my torch version from 2.1 to 1.8.  But the final results are still the same.
I haven't changed the test code. Here are the original video, extracted audio and infenrence audio:
[https://drive.google.com/drive/folders/1UPDgsh24zoDkeg9Zag_cGMmDpKGiktKV?usp=sharing](url)

**Comment by ms-dot-k** [comment]
I checked with your files, and I found that your wav file does not same with mine.
Your provided inference wav file is greatly match with mine but not your ground truth wav file.
Is it related with ffmpeg version? Mine is 3.4.11.
And I will upload the audio extraction file also.

**Comment by ms-dot-k** [comment]
https://drive.google.com/file/d/14SMCYeuAdSI04z-w_7tmOwYpUCaEhc3G/view?usp=drive_link
This is my extracted wav file which is the same sample you shared with me.
Also I uploaded `./preprocess/Extract_audio_LRS.py` and instruction in README_lrs. so please try again.

**Comment by Yifan-Liang** [comment]
Thanks! ! !
I have changed my ffmpeg version to 3.4.11 and reextracted the wav files( my old version was 1.2.6). Finally, I get the 0.405 scores which is almost same with yours. I think this problem may caused by the alignment operation.

**Comment by ms-dot-k** [comment]
That's great!!
